export { db, initializeDatabase } from './client';
export { trips, categories, activities, targets, users, sessions, savedFilters, recentSearches, settings, tripAiOverviews } from './schema';
export { seedDataIfEmpty } from './seed';
export {
  getAllTrips,
  insertTrip,
  updateTripById,
  deleteTripById,
  getAllCategories,
  insertCategory,
  updateCategoryById,
  deleteCategoryById,
  getAllActivities,
  insertActivity,
  updateActivityById,
  deleteActivityById,
  setFavouriteActivity,
  clearFavouriteActivity,
  getAiOverview,
  upsertAiOverview,
  clearAiOverview,
  getAllTargets,
  insertTarget,
  updateTargetById,
  deleteTargetById,
  findUserByEmail,
  findUserWithHashByEmail,
  findUserById,
  insertUser,
  deleteUserById,
  updateUserProfile,
  getActiveSession,
  createSession,
  clearSessionDb,
  getAllSavedFilters,
  insertSavedFilter,
  deleteSavedFilterById,
  getRecentSearches,
  insertRecentSearch,
  clearRecentSearches,
  getSetting,
  setSetting,
} from './repository';
